name: 'Setup Gradle Repo'
description: 'Checks outs the repo and sets up the JDK and Gradle.'
inputs:
  java-version:
    description: 'The JDK version to use'
    default: '21'
    required: false
  java-distribution:
    description: 'The JDK distribution to use'
    default: 'temurin'
    required: false
  fetch-depth:
    description: 'The depth of commits to fetch'
    default: '0'
    required: false
  submodules:
    description: 'Whether to fetch submodules'
    default: 'recursive'
    required: false
  build-scan-publish:
    description: 'Whether to publish build scans'
    default: 'true'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.7
      with:
        submodules: ${{ inputs.submodules }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.5.0
      with:
        build-scan-publish: ${{ inputs.build-scan-publish }}
        build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
        build-scan-terms-of-use-agree: 'yes'
