group:
  # Docs
  - files:
      - source: docs/CONTRIBUTING.md
      - source: docs/ISSUE_TEMPLATE.md
      - source: docs/PULL_REQUEST_TEMPLATE.md
    repos: |
      Oztechan/CCC
      Oztechan/Tracefit
      Oztechan/actions

  # .github
  - files:
      - source: .github/auto_assign.yml
      - source: .github/CODEOWNERS
    repos: |
      Oztechan/CCC
      Oztechan/Tracefit
      Oztechan/actions