name: Setup Gradle Repo

runs:
  using: 'composite'
  steps:
    - name: Clone Repo
      uses: actions/checkout@v4.1.4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
