name: Global Config Update
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.21.0
        with:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          PR_LABELS: "config"
          COMMIT_PREFIX: "Oztechan/Config#4 Global config update"
