name: Global Config Update
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  GlobalConfigUpdate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.21.1
        with:
          GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PR_LABELS: "config"
          COMMIT_PREFIX: "[Oztechan/Global#4] Global config update"
