name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/project-composite.yml@1d8b80970466e0520d4be348436cbdb29b974946
    with:
      project_id: 8
    secrets: inherit
