name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/project-comosite.yml@0aa97e9269a3737f254fe502b45488836698c42f
    with:
      project_id: 8
    secrets: inherit
