name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  milestone:
      runs-on: ubuntu-latest
      steps: [ run: echo ]
      outputs:
        value: ${{ secrets.MILESTONE }}

  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project.yml@develop
    with:
      project_id: 8
    secrets: inherit
