name: Publish Release

on:
  workflow_call:
    inputs:
      slack_channel:
        required: true
        type: string

jobs:

  PublishRelease:
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:

      - name: PublishRelease
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - name: Set Job Status
        id: status
        run: echo "status=success" >> $GITHUB_OUTPUT

  Notify:
    runs-on: ubuntu-22.04
    needs: [ PublishRelease ]
    if: always()
    steps:

      - name: Notify slack fail
        if: false == (needs.PublishRelease.outputs.status == 'success')
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: ${{ inputs.slack_channel }}
          status: FAILED
          color: danger
